### ISSUE TITLE
Error with Website m2o2c2 links seem to be broken

### ISSUE THREAD

**Issue by cognizac** [XimeraProject/server#102]
When attempting to reach the activities page from the coursera class at URL http://ximera.osu.edu/course/kisonecat/m2o2c2/master/course/activity/welcome/
The page says:
I am so sorry.
An internal server error has occurred.
Missing branch

Upon clicking the m2o2c2 link at the bottom of the page (http://ximera.osu.edu/course/kisonecat/m2o2c2/course/), there is an nginx 502 error:
502 Bad Gateway

**Comment by dmitrijskass** [comment]
I have the same problem, very sad..

**Comment by kisonecat** [comment]
This is followed-up in https://github.com/XimeraProject/server/issues/103
