### ISSUE TITLE
m2o2c2 error

### ISSUE THREAD

**Issue by Tierprot** [XimeraProject/server#107]
While open https://ximera.osu.edu/course/kisonecat/m2o2c2/master/course/ error is occuring: 
I am so sorry.
An internal server error has occurred.

Missing branch

**Comment by kisonecat** [comment]
That course has not been updated for the new version of Ximera.

**Comment by Tierprot** [comment]
Sorry to ask, but will you update it? The course was fantastic as i
remember.

2017-08-03 23:53 GMT+03:00 Jim Fowler <notifications@github.com>:

**Comment by kisonecat** [comment]
Yes, the plan is to update it.

**Comment by Tierprot** [comment]
Good to know - thanks in advance! Will definitely stay in touch for it!

2017-08-04 1:30 GMT+03:00 Jim Fowler <notifications@github.com>:
