### ISSUE TITLE
\graph not recognizing xmax/xmin ymax/ymin

### ISSUE THREAD

**Issue by bartsnapp** [XimeraProject/server#117]
Consider the example:
      \[
     \graph[xmin=-10, xmax=10, ymin=0, ymax=30]{y=x+4\left\{x<1\right\},y=x^2+2x+2\left\{1\leq x<3\right\},y=6x-1\left\{3 \leq x\right\}} 
      \]

here ymax is not respected,

see the bottom of 

http://ximera.osu.edu/activity/80a066ccbfe7c688fe33f2b018a549620b6c731e/continuity/digInContinuityOfPiecewiseFunctions

**Comment by kisonecat** [comment]
This is fixed by f66873a408cdc8e745f59589a976f1832b376175
