### ISSUE TITLE
/course/mooculus/calculus1/master/understandingFunctions/digInForEachInputExactlyOneOutput

### ISSUE THREAD

**Issue by serraozgen** [XimeraProject/server#119]
For the questions where I have 4 or more questions it tells me all of my answers are wrong, even though I clicked through all of them.

**Comment by bartsnapp** [comment]
Hi, this is Bart, I believe this is not a bug. Email me directly, with a screen shot of the the question and we'll get it sorted out

**Comment by bartsnapp** [comment]
You can reach me at snapp.14@osu.edu
