### ISSUE TITLE
Hitting the refresh button increments Xudos by 2

### ISSUE THREAD

**Issue by buruzaemon** [XimeraProject/server#12]
I have seen this in:
- iPhone 5S, iOS 7.1 (11D167), with the default Safari browser
- WinXP Professional, Version 2002, Service Pack 3, with Chrome

I recall seeing that someone else mentioned this bug, but allow me to repeat, just in case.

Thanks very much!

p.s. I am loving this course a lot! Hardest time I ever had in a MOOC!

**Comment by kisonecat** [comment]
Xudos have been eliminated now.
