### ISSUE TITLE
/course/mooculus/calculus1/{ repository: 'calculus1',  owner: 'mooculus',  name: 'master',  lastUpdate: Fri Aug 26 2016 08:21:31 GMT-0400 (EDT),  commit: '280f2979365fc9a1ea9933eea4a7e6a284e6049c',  __v: 0,  _id: 57c0344bfad170797b1752c0 }/reviewOfFamousFunctions/titlePage

### ISSUE THREAD

**Issue by hounshell4** [XimeraProject/server#121]
When i try to go into one of my assignments, it tells me that the page cannot be found. It was working the other day when i was working on ximera.

**Comment by bartsnapp** [comment]
Hi,

I think we just fixed that. I'll close the thread, you can email directly snapp.14@osu.edu if you have more difficulties.
