### ISSUE TITLE
/course/mooculus/calculus1/master/samplePractice/samplePractice

### ISSUE THREAD

**Issue by Brunonj** [XimeraProject/server#125]
%% g(k)=\answer{\frac{-\pi| k| }{2}}\qquad h(k) =\answer{\frac{\pi|k| }{2}} Line 266 or 267 does not work correctly.  Will not accept correct answer but will accept a blank answer.  It appears like it is commented out and should not show up at all but it does.

**Comment by bartsnapp** [comment]
Did you "update" (the orange button at the top)?

That  should fix it. Email me directly snapp.14@osu.edu if this doesn't work.
