### ISSUE TITLE
/activity/01fb6e7dfa65223fb0dd4a885e2b439d4f5ed852/polynomials/polynomials

### ISSUE THREAD

**Issue by dweathers** [XimeraProject/server#129]
Hey y'all,

When I publish & clear my cookies (new Incognito** window) I have to refresh a second time to get Desmos applets to display. This seems to be independent of the edit I just made or the window I use (same thing happens in non-Incognito window).

Thanks!

 ** The Google feature, not the man I work with.

**Comment by bartsnapp** [comment]
Hi, if you can give us a link, we can see what's going on.

**Comment by dweathers** [comment]
Hi Bart
