### ISSUE TITLE
/course/mooculus/calculus1/master/linearApproximation/digInLinearApproximation

### ISSUE THREAD

**Issue by gvalenzuelarg** [XimeraProject/server#137]
The last question of this activity doesn't seem to accept the correct answer

**Comment by bartsnapp** [comment]
Ah - I need to add more information to the problem. You are at x=1. I've corrected this, in the sense that I've added more info to the problem. Now that you know we are at the point x=1, you should be able to answer it correctly. You can avoid updating by typing in .2
