### ISSUE TITLE
\includegraphics width

### ISSUE THREAD

**Issue by sergeballif** [XimeraProject/server#14]
The width parameter in \includegraphics doesn’t seem to do anything in Ximera. Do we need to create images at the exact desired size? Should the default display option for the image environment be a centered image? A centered image would be our preference.

**Comment by kisonecat** [comment]
https://github.com/XimeraProject/server/commit/8d7fcac59bafd87f834ca974eacdbde6f7bf8c94 also fixes the aspect ratio issues.

Given "responsive design" and the issue that we don't know what size screen anything will be viewed on (e.g., phones versus TVs), I think this is the best we can do.
