### ISSUE TITLE
"Report error in content" bug report option not functioning

### ISSUE THREAD

**Issue by JukeboxRhino** [XimeraProject/server#143]
[server/views/course/activity.jade:24](https://github.com/XimeraProject/server/blob/master/views/course/activity.jade#L24)
For example, clicking on that button currently gives the link
```https://github.com/undefined/undefined/issues/new?title=The%20%20cross%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20product&body=%0A%0ASee%20[crossProducts/digInCrossProducts.tex](https://github.com/undefined/undefined/blob/1c0679aa57e4bc8a45946be7380ab64caf29d86c/crossProducts/digInCrossProducts.tex)```

**Comment by kisonecat** [comment]
The commit https://github.com/XimeraProject/server/commit/f6bca22ee6b2ba20822d3e444e41e5ec31c1d977 fixes the crazy number of spaces.  The "undefined" problem is fixed by the new metadata backend in xake.
