### ISSUE TITLE
math mode backslashes in \# or \%

### ISSUE THREAD

**Issue by sergeballif** [XimeraProject/server#15]
Some commands in math mode don’t display correctly in Ximera. For example # or \% will display with the backslash. Also the \text{} command inside of math mode doesn’t behave perfectly. You can’t use an \emph{} command inside \text{} inside of math mode.

**Comment by kisonecat** [comment]
The good news is that I now get
```
You can't use `macro parameter character #' in restricted horizontal mode.
```
when I try to use a naked # in mathmode.
