### ISSUE TITLE
/users/59753b49716698476e7393c0

### ISSUE THREAD

**Issue by George0805** [XimeraProject/server#157]
Hi,

Thank you for reading my message. I've been using XimeraProject for about 2 months and I really enjoyed the learning experience. But today when I'm logging in to the website I found all my study progress has gone. This really scary because I intended to use the certificate at the end of the course for my grad school application. So, could you help me if there is any possibility to recover my progress in terms of Calculus 1 and 2? It means a lot to me.

Thank you again!
George Li

**Comment by George0805** [comment]
The url below is the original link I found in my previous Ximera webpage. Not valid anymore.
https://ximera.osu.edu/users/59223ea342c381622c184b2b

**Comment by kisonecat** [comment]
I will help you with this over email.
