### ISSUE TITLE
Aspect ratio of \includegraphics

### ISSUE THREAD

**Issue by bartsnapp** [XimeraProject/server#164]
This is sometimes messed up... It seems dependent on the width of the window. 

However, \includegraphics within a tabular environment seem to maintain the aspect ratio... 

Could be a ximera.cls issue.

**Comment by bartsnapp** [comment]
Perhaps a ?simple? fix would be to make the image command place all graphics with in a <Table> ??

**Comment by kisonecat** [comment]
https://github.com/XimeraProject/server/commit/8d7fcac59bafd87f834ca974eacdbde6f7bf8c94 fixes this.
