### ISSUE TITLE
Renaming Repository Breaks Links

### ISSUE THREAD

**Issue by hparshall** [XimeraProject/server#17]
Created "Hans Test Course" with the repository hparshall/git-pull-request

Renamed hparshall/git-pull-request to hparshall/ximeraTestCourse

Link from Ximera page goes to:

http://ximera.osu.edu/course/hparshall/git-pull-test/course/

but should go to:

http://ximera.osu.edu/course/hparshall/ximeraTestCourse/course/

Maybe we need a way to delete our courses?  Courses with a name that already exists don't indicate this.

**Comment by kisonecat** [comment]
The new xake deployment addresses this.
