### ISSUE TITLE
/mooculus/projects/calculus3/projectBuckeyeVR/projectBuckeyeVR

### ISSUE THREAD

**Issue by anapanic** [XimeraProject/server#174]
I cannot access this link to my project instructions, I need to it in order to finish the assignment! Please help open it.

**Comment by bartsnapp** [comment]
Hi Ana,
We're working to fix this quickly.
Keep in mind the project isn't due until Oct 6th. However, if you need to do it now, you can simply used the PDF instructions posted on
Carmen -> Modules -> Projects -> projectBuckeyeVR.pdf

**Comment by bartsnapp** [comment]
It's fixed now. The issue was a misconfigured server at ASCTech
