### ISSUE TITLE
nodejs vs node

### ISSUE THREAD

**Issue by hparshall** [XimeraProject/server#18]
At least for Debian based systems, node is the legacy binary for nodejs.  See:

http://stackoverflow.com/questions/21168141/can-not-install-packages-using-node-package-manager-in-ubuntu

Either nodejs should be used in place of node, or debian users should install the package "nodejs-legacy"

**Comment by kisonecat** [comment]
This is fixed in https://github.com/XimeraProject/server/blame/master/README.md#L46
