### ISSUE TITLE
Matrix Answer Buttons

### ISSUE THREAD

**Issue by hparshall** [XimeraProject/server#19]
Buttons to add rows and columns are "backwards"

Current behavior:
Plus/minus buttons on the bottom are horizontal and add columns
Plus/minus buttons on the right are horizontal and add rows

Expected behavior:
Plus/minus buttons on the bottom should be vertical (maybe) and add rows (definitely)
Plus/minus buttons on the right should remain horizontal and add columns

**Comment by kisonecat** [comment]
The matrix answer type is gone, and is being completely rewritten for the upcoming linear algebra course on ximera.
