### ISSUE TITLE
/mooculus/understandingFunctions/exercises/exerciseList/lti

### ISSUE THREAD

**Issue by jschnipke98** [XimeraProject/server#194]
You guys don't have the server capacity to run this website. Just a guess  I get server error 500 all the time and it isn't even saving anymore.

**Comment by kisonecat** [comment]
Unfortunately nginx has exceeded a limit on the number of open files (nginx error 24).  Once nginx is reconfigured, everything should return to normal.

**Comment by jschnipke98** [comment]
How fast would that take to reconfigure?

**Comment by kisonecat** [comment]
It can be done very quickly, but I don't have the necessary permissions.

**Comment by kisonecat** [comment]
It should be working again.  Please try it, and if you are still having trouble, please let me know.
