### ISSUE TITLE
/mooculus/calculusAndVectorValuedFunctions/exercises/exerciseList/calculusAndVectorValuedFunctions/exercises/vectorValuedLimitTrig.ditto

### ISSUE THREAD

**Issue by SeanZhangCSE** [XimeraProject/server#198]
Question 10 and 21 in HW6 have errors! Correct answers are not accepted.

**Comment by bartsnapp** [comment]
I just checked out 10, and  21 --- they looked ok 

21 had a minor typo (in the statement), but not with the answers...

Is there an orange update button? If so, you should push it. (I know it will give you a warning, push it anyway)
