### ISSUE TITLE
/mooculus/implicitDifferentiation/exercises/exerciseList/implicitDifferentiation/exercises/derivativesOfLogsAndExp

### ISSUE THREAD

**Issue by yates259** [XimeraProject/server#218]
3rd part of exercise is all messed up and I don't know what to put where

**Comment by bartsnapp** [comment]
I just checked it out, it looked ok-- is there an orange update button, if do push it, and the problem will be readable.

**Comment by yates259** [comment]
Will it reset my progress for the whole assignment if i do that?

________________________________

**Comment by bartsnapp** [comment]
Here is what will (and will not) happen:

*) Your grade on Carmen will not be affected.
*) It will delete your work on this page, but no other pages. But your current record of completion will remain.
*) To complete this page, you will need to answer all 4 problems on this specific page once again.
