### ISSUE TITLE
Too permissive validator

### ISSUE THREAD

**Issue by bartsnapp** [XimeraProject/server#222]
This  blank is also too permissive
https://ximera.osu.edu/mooculus/calculus3/multipleIntegrals/digInIntegralsOverTrivialRegions

![mayaanti](https://user-images.githubusercontent.com/1376703/36927922-08abbd46-1e4f-11e8-9163-d87a2422e66d.png)

it validates xy+e^y = xy^2/2 + e^y

**Comment by kisonecat** [comment]
https://github.com/kisonecat/math-expressions/commit/1c2b7a7849bc2583e747580ee506d5b48a76546f fixes this, but unfortunately we haven't integrated the newest version of math-expressions into Ximera.  Hopefully soon.
