### ISSUE TITLE
/mooculus/calculus1/meanValueTheorem/digInExtremeValueTheorem

### ISSUE THREAD

**Issue by CH41NS0L** [XimeraProject/server#226]
When I try to put in the first x value on the Question "Find the x-coordinate(s) of the point(s) where the function f has a global minimum. ", the page just resets as if I reloaded it, using Firefox Quantum 59.0.1 (64-bit).

**Comment by bartsnapp** [comment]
I just checked it out - it looked ok. However, I made some minor changes. 
I think you just got unlucky and were attempting to work on this as the back-end was redeployed. 
Please check it out once more, and let us know if you are still having trouble.
