### ISSUE TITLE
/mooculus/computationsForGraphingFunctions/exercises/exerciseList/computationsForGraphingFunctions/exercises/graphingComputations7

### ISSUE THREAD

**Issue by gnoeth** [XimeraProject/server#227]
Every time I press enter or the question button, it reloads the page and doesn't check my answer it just erases it.

**Comment by kisonecat** [comment]
Can you try a force refresh (e.g., shift-control-R)?  I recently deployed some new backend code...

**Comment by gnoeth** [comment]
I just did the force refresh and it’s still refreshing the page when I answer.

On Mar 18, 2018, 7:05 PM -0400, Jim Fowler <notifications@github.com>, wrote:

Can you try a force refresh (e.g., shift-control-R)? I recently deployed some new backend code...

**Comment by kisonecat** [comment]
I can reproduce this, and https://github.com/XimeraProject/server/commit/0838bc1dc5129dc777916ddef172cd632f5338ee fixes it on my end.  Try another force-refresh and it should work.

I very much appreciate your taking the time to report this bug!
