### ISSUE TITLE
/mooculus/introductionToTaylorSeries/exercises/exerciseList/introductionToTaylorSeries/exercises/calculateATaylorPolynomialGuided

### ISSUE THREAD

**Issue by nellyneil** [XimeraProject/server#263]
First portion of the problem is intended to be a multi-select problem but I can only select one choice per submission. Choosing choice 2 or 3 will grade the problem as correct, but I think it's intended for choices 2 and 3 to both be selected, not one or the other. 

https://i.gyazo.com/25172402a0f33d41d08470d3e21e23d1.mp4

**Comment by bartsnapp** [comment]
Fixed!
