### ISSUE TITLE
/mooculus/introductionToTaylorSeries/exercises/exerciseList/introductionToTaylorSeries/exercises/calculateATaylorPolynomialGuided

### ISSUE THREAD

**Issue by nellyneil** [XimeraProject/server#264]
Answer is wrong, should be 5+x+4/3x^3+5/6x^4 not 5+2x+...

![error](https://user-images.githubusercontent.com/32889641/42416525-19dade72-823f-11e8-9839-6e4abfff2912.png)

**Comment by bartsnapp** [comment]
Fixed thanks!
