### ISSUE TITLE
/mooculus/numericalMethods/exercises/exerciseList/numericalMethods/exercises/understandingMathematicalLanguage

### ISSUE THREAD

**Issue by YixianHe1252** [XimeraProject/server#269]
This is homework for math 1152 direction field in Ximera. The first blank in the first question will never go right.

**Comment by bartsnapp** [comment]
Thanks for reporting that. I believe I've fixed it. You'll have to press the orange update button to see the fix. While this will delete your work on this page, it will not delete the record of completion or any other work done on the site.
