### ISSUE TITLE
Eventaully, we need a way to create assignments

### ISSUE THREAD

**Issue by rpruim** [XimeraProject/server#27]
I'm imagining an assignment includes (at least):
- a set of problems to do 
- a due date
- some information about behaviors (like number of attempts allowed, etc.)
- data base hooks about how things should be graded (it should be easy for instructors to get a score for each student on each assignment)
- bread crumbs for some sort of navigation system

Others can add additional ideas about what should be part of the assignment structure.

**Comment by kisonecat** [comment]
Due dates are handled via LTI (e.g., Canvas passes them back) and the grades are passed back to an LTI-compatible gradebook as well.

Files with \documentclass{xourse} can be used to make a set of problems or pages to complete.
