### ISSUE TITLE
/mooculus/calculusEPart1

### ISSUE THREAD

**Issue by montgomerygavin** [XimeraProject/server#284]
Good afternoon, 

I completed my assignment, Textbook Part 1, for Math 1172 a few days ago. However, the last portion of the assignment, "A review of integration techniques", is only displaying that about 64% of it is completed, despite the fact that every box is filled in correctly and has a green check mark next to it. Because of this, my final score for the assignment totals 94.45%, instead of 100%. 

Sincerely,
Gavin Montgomery
montgomery.1052@osu.edu

**Comment by bartsnapp** [comment]
Hi,
I'm very sorry you are having this problem... 
There is a temporary fix... hit the red erase button. 
then type in your answers once more. I bet it will work.

We do not consider this to be a real fix and are still working to understand why this is happening to some people.

**Comment by montgomerygavin** [comment]
Thank you for your help. I just re-did the assignment and it appears to be 100% now.

Gavin Montgomery
montgomery.1052@osu.edu

________________________________

**Comment by bartsnapp** [comment]
Great. We are still working on this so that it stops happening for good.
