### ISSUE TITLE
/mooculus/calculusEPart1/aReviewOfIntegration/digInAReviewOfIntegrationTechniques

### ISSUE THREAD

**Issue by ElRoberto13** [XimeraProject/server#286]
I complete every part of this section but the green progress bar is still not 100% full and my grade on the assignment is therefore listed as 99%, not 100%. Everything Ientered was marked as correct so there must be a bug preventing the section from being 
![764ccb63-804b-478f-84bf-04bd8d4761d1](https://user-images.githubusercontent.com/42687232/44613936-bde63780-a7e9-11e8-8f18-9ca6a34f8600.png)
![a9ca46cf-2c6e-4fe1-8a64-b516861a61b4](https://user-images.githubusercontent.com/42687232/44613937-bde63780-a7e9-11e8-8562-3c1737f0e5d3.png)
![5126f639-b4dd-4ca9-be97-cfff04fd41ce](https://user-images.githubusercontent.com/42687232/44613938-bde63780-a7e9-11e8-9a2c-c38ff4d45c2f.png)
![1378ca59-3f45-4d97-8a54-4505d86899bd](https://user-images.githubusercontent.com/42687232/44613939-bde63780-a7e9-11e8-8f2f-1e47a44e24cd.png)
![6c7d1468-bd6d-4e6d-8595-5fc655778360](https://user-images.githubusercontent.com/42687232/44613940-bde63780-a7e9-11e8-8e97-fe7d798fa106.png)
![21b9a2d5-ee58-4da6-b8c7-13eaba04fcd2](https://user-images.githubusercontent.com/42687232/44613941-bde63780-a7e9-11e8-9192-83723e1c7099.png)

100% complete.

**Comment by bartsnapp** [comment]
Hi, yes this is a new bug...

We are working on it.

Currently you have two options:

1) Don't worry about it (you are close enough)
2) hit the erase button, type your work in again, and then I think it will fill up.

I know this is distressing, and I think this will be fixed soon, but right now, this is what we have.

The course coordinators are aware of this, and definitely will take this into consideration when assigning grades.

**Comment by bartsnapp** [comment]
At this point in time, the bug has been fixed.
The change to the server d1a001a should ensure that this does not happen again.

However, you will need to erase and redo the portion of your homework that previously was not recording.

If the due date has already passed, contact your instructor.

We apologize for the inconvenience.
