### ISSUE TITLE
/mooculus/review/refreshPrerequisites/exerciseList/review/refreshPrerequisites/substitution

### ISSUE THREAD

**Issue by maxwellpaul560** [XimeraProject/server#288]
The progress bar as well as my reported grade is not reflecting my progress on the assignment review 1

**Comment by bartsnapp** [comment]
Thanks for reporting this. This is a known bug.

At this point in time, the bug has been fixed.
The change to the server d1a001a should ensure that this does not happen again.

However, you will need to erase and redo the portion of your homework that previously was not recording.

If the due date has already passed, contact your instructor.

We apologize for the inconvenience.
