### ISSUE TITLE
/mooculus/understandingFunctions/exercises/exerciseList

### ISSUE THREAD

**Issue by joshsmith18** [XimeraProject/server#289]
I'm working on my calculus 1 homework and it should be 100% comlete because I have no more problems left to do, but it still says I have things to complete, please help me

**Comment by bartsnapp** [comment]
Thanks for reporting this. This is a known bug.

At this point in time, the bug has been fixed.
The change to the server d1a001a should ensure that this does not happen again.

However, you will need to erase and redo the portion of your homework that previously was not recording.

If the due date has already passed, contact your instructor.

We apologize for the inconvenience.
