### ISSUE TITLE
/mooculus/calculus2Part1/aReviewOfIntegration/digInAReviewOfIntegrationTechniques

### ISSUE THREAD

**Issue by jbianco2** [XimeraProject/server#290]
Have all the questions completed, only shows a 93%

**Comment by bartsnapp** [comment]
Thanks for reporting this. This is a known bug.

At this point in time, the bug has been fixed.
The change to the server d1a001a should ensure that this does not happen again.

However, you will need to erase and redo the portion of your homework that previously was not recording.

If the due date has already passed, contact your instructor.

We apologize for the inconvenience.
