### ISSUE TITLE
/mooculus/aReviewOfIntegration/exercises/exerciseList

### ISSUE THREAD

**Issue by sammers610** [XimeraProject/server#292]
I was 24/25 problems deep and then the site crashed and deleted all my answers. I have been doing this assignment over the course of the day and have saved every page. Is there anything I can do because it took a while.

**Comment by bartsnapp** [comment]
I'm sorry, it is most likely gone.
Please talk to your instructor, they should be understanding.

The issue that caused this bug has been resolved. 
The change to the server d1a001a should ensure that this does not happen again.
