### ISSUE TITLE
/mooculus/whatIsALimit/exercises/exerciseList

### ISSUE THREAD

**Issue by adelepohl** [XimeraProject/server#293]
I filled out all of problem #2 but the green bar isn't appearing even though I repeatedly tried saving it. Now I have an 8.5/10 for my grade even though I fully completed the assignment and did all the questions for #2.
![screen shot 2018-08-27 at 5 11 46 pm](https://user-images.githubusercontent.com/42755483/44691843-405f3900-aa2e-11e8-9c45-2693c5767254.png)
![screen shot 2018-08-27 at 5 11 27 pm](https://user-images.githubusercontent.com/42755483/44691844-405f3900-aa2e-11e8-8bdc-9f125796cace.png)
![screen shot 2018-08-27 at 5 10 40 pm](https://user-images.githubusercontent.com/42755483/44691845-405f3900-aa2e-11e8-99e6-b387ae1ecf57.png)
![screen shot 2018-08-27 at 5 10 36 pm](https://user-images.githubusercontent.com/42755483/44691847-405f3900-aa2e-11e8-8d1d-b08f25a503d0.png)
![screen shot 2018-08-27 at 5 10 28 pm](https://user-images.githubusercontent.com/42755483/44691848-405f3900-aa2e-11e8-9407-286f4164233f.png)
![screen shot 2018-08-27 at 5 10 08 pm](https://user-images.githubusercontent.com/42755483/44691849-405f3900-aa2e-11e8-9592-6fc0cff75308.png)
![screen shot 2018-08-27 at 5 09 24 pm](https://user-images.githubusercontent.com/42755483/44691850-405f3900-aa2e-11e8-8525-662cb2acbe3b.png)

**Comment by bartsnapp** [comment]
Greetings,

Thanks for reporting this. This is a known bug.

At this point in time, the bug has been fixed.
The change to the server d1a001a should ensure that this does not happen again.

However, you will need to erase and redo the portion of your homework that previously was not recording.

If the due date has already passed, contact your instructor.

We apologize for the inconvenience.
