### ISSUE TITLE
/mooculus/understandingFunctions/exercises/exerciseList/understandingFunctions/exercises/trigReview1

### ISSUE THREAD

**Issue by ZuoTan** [XimeraProject/server#294]
I finished my math task on Carmen, but there is one section that I did type all the answer right but did not give me any score.

**Comment by bartsnapp** [comment]
Greetings,

Thanks for reporting this. This is a known bug.

At this point in time, the bug has been fixed.
The change to the server d1a001a should ensure that this does not happen again.

However, you will need to erase and redo the portion of your homework that previously was not recording.

If the due date has already passed, contact your instructor.

We apologize for the inconvenience.
