### ISSUE TITLE
/mooculus/whatIsALimit/exercises/exerciseList

### ISSUE THREAD

**Issue by QixuanWei** [XimeraProject/server#295]
When i finished What is a limit, i found out that i couldn't upload half my answers. I finished all the questions but it shows that i only finished half of them and got half grades. I believe there must be some technical issues. Please help me.

**Comment by bartsnapp** [comment]
Greetings,

Thanks for reporting this. This is a known bug.

At this point in time, the bug has been fixed.
The change to the server d1a001a should ensure that this does not happen again.

However, you will need to erase and redo the portion of your homework that previously was not recording.

If the due date has already passed, contact your instructor.

We apologize for the inconvenience.
