### ISSUE TITLE
/mooculus/aReviewOfIntegration/exercises/exerciseList/aReviewOfIntegration/exercises/3ExamplesOfArctan

### ISSUE THREAD

**Issue by laurenkins** [XimeraProject/server#296]
I have successfully completed the questions, but the bar will not fill up, and the points have not been given.

**Comment by laurenkins** [comment]
I looked at the other issues' solutions and tried erasing and resubmitting. It worked. Thank you!

**Comment by kisonecat** [comment]
I am glad that this helped.  The change to the server https://github.com/XimeraProject/server/commit/d1a001a13b18f7a3837b98bac23723b3b22f793f should ensure that this does not happen again.

If you ever run into trouble again, please let me know.  We are very much committed to making sure that this system works well and saves students from having to purchase expensive commercial homework codes.
