### ISSUE TITLE
/mooculus/whatIsALimit/exercises/exerciseList/whatIsALimit/exercises/continuityFromGraph1

### ISSUE THREAD

**Issue by XuanHe2345** [XimeraProject/server#297]
I have finished all the questions in question 7 but I do not get my points. It keeps appearing I do not finish question 7.

**Comment by bartsnapp** [comment]
Greetings,

Thanks for reporting this. This is a known bug.

At this point in time, the bug has been fixed.
The change to the server d1a001a should ensure that this does not happen again.

However, you will need to erase and redo the portion of your homework that previously was not recording.

If the due date has already passed, contact your instructor.

We apologize for the inconvenience.
