### ISSUE TITLE
/mooculus/limitLaws/exercises/exerciseList/limitLaws/exercises/limitFromTable2

### ISSUE THREAD

**Issue by schwarz145** [XimeraProject/server#299]
Module 7 is not giving me credit for completed work.

**Comment by bartsnapp** [comment]
Greetings,

Thanks for reporting this. This is a known bug.

At this point in time, the bug has been fixed.
The change to the server d1a001a should ensure that this does not happen again.

However, you will need to erase and redo the portion of your homework that previously was not recording.

If the due date has already passed, contact your instructor.

We apologize for the inconvenience.
