### ISSUE TITLE
/mooculus/limitLaws/exercises/exerciseList/limitLaws/exercises/Q1SP17REDUX

### ISSUE THREAD

**Issue by Rithvikt17** [XimeraProject/server#300]
I have been trying to complete the Online Homework: Limit Laws but I keep facing technical problems. 

Question 7 in the worksheet only shows one initial table (which I have completed), however, I know that there are more sub-parts in Q7 because when the page loads, for a brief moment I can see the other questions before they disappear. 

Question 9. No matter how many times I complete it, the green bar showing progress never fills. 

If I check my grade on Carmen, it shows an 8.52/10 because I wasn't able to complete this worksheet due to these technical problems.

Is there anything I can do?

I have attached screenshots to this mail as well.
![screenshot 240](https://user-images.githubusercontent.com/42760416/44737360-c6779000-aabf-11e8-9d41-22ed0ee4ad0e.png)
![screenshot 241](https://user-images.githubusercontent.com/42760416/44737361-c6779000-aabf-11e8-9ebc-c27cc0da3a34.png)
![screenshot 242](https://user-images.githubusercontent.com/42760416/44737362-c6779000-aabf-11e8-82dd-8c9bd980b8ed.png)

**Comment by bartsnapp** [comment]
Greetings,

Thanks for reporting this. This is a known bug.

At this point in time, the bug has been fixed.
The change to the server d1a001a should ensure that this does not happen again.

However, you will need to erase and redo the portion of your homework that previously was not recording.

If the due date has already passed, contact your instructor.

We apologize for the inconvenience.
