### ISSUE TITLE
/mooculus/review/refreshSquareRoots/exerciseList/review/refreshSquareRoots/distributiveErrorIntegral

### ISSUE THREAD

**Issue by RobertWetzler** [XimeraProject/server#317]
When I try to type something into the box for “u = “ and i tap the blue button to check my answer, the page reloads and deletes my answer, preventing me from progressing on the page. Also, i’m the sentence following the box, there is red text that says something like [Math Processing Error]

**Comment by ElRoberto13** [comment]
I think the Math Parser just isn’t functioning on this page for me

**Comment by kisonecat** [comment]
What browser are you using?
