### ISSUE TITLE
\%, \$, and \# don't work (consistently) in math mode

### ISSUE THREAD

**Issue by sergeballif** [XimeraProject/server#33]
Some of the time the commands \%, \$, and # don't typeset correctly for me (though I can see instances where they display just fine). In particular, in math mode with the \text{} command they seem to fail a lot. See http://ximera.osu.edu/course/sergeballif/NSC-Math-120/course/activity/ConditionalProbabilities/IntroToConditional/ for an example where # fails.

**Comment by kisonecat** [comment]
I am glad that avoiding \text is helping here.
