### ISSUE TITLE
/mooculus/rulesOfDifferentiation/exercises/exerciseList/rulesOfDifferentiation/exercises/

### ISSUE THREAD

**Issue by alexmcorange** [XimeraProject/server#330]
When answer is entered, the page refreshes instead of verifying whether the answer is correct or not. 
Previous saved answers do not show up on screen despite reloading page.

**Comment by bartsnapp** [comment]
Hi,

Which number in particular? All of them? I just checked a few and they worked for me....

also which browser are you using?
