### ISSUE TITLE
/mooculus/review/refreshSquareRoots/exerciseList

### ISSUE THREAD

**Issue by paultauras** [XimeraProject/server#331]
I received a 100% on the assignment, Review 2: Square Roots, and in the grades section it says I received a 0/40. My professor said it mostly likely a glitch in the system and to contact Ximera. It would be greatly appreciated if this error could be fixed.

Thanks,
Paul Tauras

**Comment by bartsnapp** [comment]
Hi,
Contact your instructor, they can fix this.

**Comment by bartsnapp** [comment]
I see you contacted your instructor - sorry! Tell me who they are and I'll explain the situation.

**Comment by bartsnapp** [comment]
It is probably best to email me directly,

snapp.14@osu.edu

And tell me who you are.

That will make this easiest to fix.
