### ISSUE TITLE
tables lose details and have bad spacing

### ISSUE THREAD

**Issue by sergeballif** [XimeraProject/server#34]
It seems that the tables are converted to html tables. This loses all of the nice LaTeX typesetting. For example at http://ximera.osu.edu/course/sergeballif/NSC-Math-120/course/activity/ConditionalProbabilities/IntroToConditional/ we have a table that had colored cells that don't show up. It would be nice if the table would build as an image that gets included. At this point we will probably have to create extra images ourselves, but any advice would be appreciated.

**Comment by kisonecat** [comment]
The tables are now handled via bootstrap as of https://github.com/XimeraProject/server/commit/7d1fa4dc152183f81467943899d7b5a9f83a630e so things are a bit better now.  \textcolor also works.
