### ISSUE TITLE
/mooculus/appliedRelatedRates/exercises/exerciseList/appliedRelatedRates/exercises/singVarCalcRelatedRates1

### ISSUE THREAD

**Issue by davis2562** [XimeraProject/server#344]
I cannot submit problems 7,8,9 and 10. This happened previously as well. If i select the ? to submit the problem it just pulls up the "Are you sure you want to Leave this page without saving" box and will not let me submit my answers.

**Comment by bartsnapp** [comment]
Hmm 


Try a hard refresh:

Windows: ctrl + F5
Mac/Apple: Apple + R or command + R
Linux: F5

**Comment by davis2562** [comment]
that worked! You can disregard my last issue, I didn't see your response. =\ Thanks!

**Comment by bartsnapp** [comment]
Oh that's great!!!

I'm sorry you had the problem, and I'm happy the fix worked!
