### ISSUE TITLE
/mooculus/solidsOfRevolution/exercises/exerciseList/solidsOfRevolution/exercises/thinkAboutIt1

### ISSUE THREAD

**Issue by johnsojh** [XimeraProject/server#378]
The two images for this problem are not displaying (checked on both Safari and Chrome). When the problem is loaded I see the following image:
<img width="1006" alt="svg-viewer needed" src="https://user-images.githubusercontent.com/468868/51129352-3fba1a00-17f8-11e9-97ec-44dac04097ce.png">

**Comment by bartsnapp** [comment]
Fixed!
