### ISSUE TITLE
Implement Problem, Parts, Hints

### ISSUE THREAD

**Issue by hparshall** [XimeraProject/server#38]
The `problem`, `parts`, and `hints` environments have been added to ximera.cls.  I'm hoping that `problem` will take the place of the current `exercise`, `question`, and `exploration` environments.  The only current difference between these environments is labeling, which could instead be an option added to the `problem` environment.

Ideally the LaTeX code here:

https://github.com/hparshall/ximeraClassTest/blob/master/problemformat.tex

would produce online output comparable to the PDF here:

https://github.com/hparshall/ximeraClassTest/blob/master/problemformat.pdf

Problems should be labeled sequentially (1,2,3,...), even if content appears between them.  Problems cannot be nested.

Parts should be labeled sequentially (a, b, c,...), even if content appears between them.  Parts are expected to exist within a `problem` environment.  Parts cannot be nested (maybe we'll add this in the future, but one thing at a time).

Hints in a list should be revealed one at a time.  I would prefer disabling nesting of hints, but Steve really likes them, so maybe there's a way to implement nested hints logically.

**Comment by kisonecat** [comment]
And parts is dead.
