### ISSUE TITLE
/mooculus/calculus3/linesAndCurvesInSpace/digInLinesAndCurvesInSpace

### ISSUE THREAD

**Issue by ams261sbu** [XimeraProject/server#389]
In $5.1, the question is incomplete.  There should be a question asking, "These two planes intersect at a line. Find the equation of the intersecting line."  Please see the attached image for details
![incompplete](https://user-images.githubusercontent.com/47549811/52750326-f0633700-2fb9-11e9-957c-0c00a7d811e3.jpg)
.

**Comment by bartsnapp** [comment]
Hi, this problem has been fixed. You'd have to hit the orange update button to see it. If you have finished the page, you can choose to with push it or not.

Thanks for pointing it out though.

**Comment by ams261sbu** [comment]
Saw it after the upgrade!  Thanks.

Jerry
