### ISSUE TITLE
Cosmetic issue: Can we offset hints?

### ISSUE THREAD

**Issue by sergeballif** [XimeraProject/server#39]
Could we change the hints so that they are set apart from the other text? (Maybe put the text in italics or in a box or display the word "Hint:" like in the LaTeX document.) Currently it is very hard to see where the questions start or end, and where the hints start or end. 

Another cosmetic issue is that itemized lists have bullets way out in the margin and no indentation It would be nice if they looked a bit more like the default LaTeX list.

**Comment by kisonecat** [comment]
I think the new disclosure-triangle layout for hints should address this.
