### ISSUE TITLE
/mooculus/powerSeries/exercises/exerciseList/powerSeries/exercises/radiusAndIntervalOfConvergenceGuidedE

### ISSUE THREAD

**Issue by TheStrikeEagle** [XimeraProject/server#390]
The website does not load correctly, answer boxes are off the page, answers are not registering, and words overlap each other. This also appears in part 6 of the 1172 textbook.

**Comment by bartsnapp** [comment]
I confirm this bug. Looking into it.

**Comment by bartsnapp** [comment]
Ok! I believe this has been fixed! You'll have to hit the orange "update" button to see the change.
