### ISSUE TITLE
math in choices

### ISSUE THREAD

**Issue by bartsnapp** [XimeraProject/server#41]
Math mode doesn't seem to be rendering correctly when placed in multiple choice - 

This seems to be either new, or something that doesn't always happen. 

For an example, see 

http://ximera.osu.edu/course/bartsnapp/ximeraCalculusPrelectures/course/activity/definitionOfLimits/definitionOfLimits/

**Comment by kisonecat** [comment]
The new mathjax code should have fixed this.
