### ISSUE TITLE
/mooculus/logarithmicDifferentiation/exercises/exerciseList/logarithmicDifferentiation/exercises/inversesExpLog3

### ISSUE THREAD

**Issue by flinner17** [XimeraProject/server#419]
Hello, I have a very very frequent issue when completing my calculus homework on ximera. When entering my answers into the check box, sometimes when I press enter or click the question mark it just reloads the problem and resets the answer box. I have to press enter many many times until randomly it stops refreshing. 

Also, I know that this problem is going to happen when there is no preview pop up for what I have entered into the box. Please solve!! It’s making calculus much harder than it needs to be :(

**Comment by bartsnapp** [comment]
This typically happens when you are behind a VPN. Are you? 
If not (and you are at OSU Columbus' campus) maybe you could stop by my office and show me?

Also check out https://go.osu.edu/ximerahelp
