### ISSUE TITLE
/mooculus/calculus3/linesAndCurvesInSpace/digInLinesAndCurvesInSpace

### ISSUE THREAD

**Issue by reslymatog** [XimeraProject/server#431]
Three short fixes:

(1) In the section "Lines in space", after the first set of questions the following text appears:

"Here we see vectors p and q. In blue below we see the vector t(p-q) starting at point p. Convince yourself that l(t) = p + t(p-q) draws a line."

The two instances of p-q in this quotation should be q-p.

(2) Moreover, in the interactive immediately following this quotation in (1), the diagram is labeled with a t(P-Q) that should actually read t(Q-P).

(3) Immediately following the interactive mentioned in (2), there is a complete sentence that makes sense. After a period, this is followed by a sequence of words that is not a sentence.

---

Don't worry: the remaining questions in this section agree with the explanation if it is fixed according to (1), (2), (3).

---
(4) In the section "Distance between a point and a line", I am not getting the answer for the last question in the section. The t value I get is 14/3, which is not the -1 required to get the answer that is set. Suggestion to fix: If you change <-1, -1, 1> to <-1, -1, 14/3> in the problem setup and the third component of the answer to -8/3, that would fix it.

**Comment by bartsnapp** [comment]
Sorry for the delay:


> (1) In the section "Lines in space", after the first set of questions the following text appears:
> "Here we see vectors p and q. In blue below we see the vector t(p-q) starting at point p. Convince 
> yourself that l(t) = p + t(p-q) draws a line."
>The two instances of p-q in this quotation should be q-p.

Fixed!


> (2) Moreover, in the interactive immediately following this quotation in (1), the diagram is labeled with > a t(P-Q) that should actually read t(Q-P).

Fixed!

> (3) Immediately following the interactive mentioned in (2), there is a complete sentence that makes
> sense. After a period, this is followed by a sequence of words that is not a sentence.

Fixed!

> (4) In the section "Distance between a point and a line", I am not getting the answer for the last 
> question in the section. The t value I get is 14/3, which is not the -1 required to get the answer that is 
> set. Suggestion to fix: If you change <-1, -1, 1> to <-1, -1, 14/3> in the problem setup and the third 
> component of the answer to -8/3, that would fix it.

I don't think you are correct here. If you disagree with me, either show me a plot demonstrating that you are correct, or compute the necessary distances and proved that you are correct. 


Thanks and all the best!
