### ISSUE TITLE
latex comments appear in activity summary

### ISSUE THREAD

**Issue by nilesjohnson** [XimeraProject/server#46]
See attached picture:  Latex comments in the abstract section of the tex source show up in the activity summary html.

![screen shot 2014-08-28 at 3 42 31 pm](https://cloud.githubusercontent.com/assets/3353209/4081863/af9784ac-2eeb-11e4-81d5-7c059a436876.png)

**Comment by kisonecat** [comment]
The new \begin{abstract} command fixes this.
