### ISSUE TITLE
/mooculus/trigonometricSubstitution/exercises/exerciseList/trigonometricSubstitution/exercises/trigSub4

### ISSUE THREAD

**Issue by noahgarrick** [XimeraProject/server#468]
![Screen Shot 2020-09-28 at 9 37 51 AM](https://user-images.githubusercontent.com/72026392/94439397-5c35eb80-016e-11eb-9297-565bcb149094.png)
The website keeps "completing" my work, and every time I move on to a new question, it automatically completes it. I've tried exiting out and restarting Carmen, but nothing is working. How do i undo this?

**Comment by bartsnapp** [comment]
Bad news -- this is due to a browser setting at your end. 

two fixes:
Use a new browser or
check this out:

https://go.osu.edu/ximerahelp
