### ISSUE TITLE
Optional arguments to definition environment don't show in html

### ISSUE THREAD

**Issue by nilesjohnson** [XimeraProject/server#47]
When my tex source has

```
\begin{definition}[Homology]
  $H_n = Z_n/B_n$ 
\end{definition}
```

I get something like this in pdf:

![screen shot 2014-08-28 at 4 14 17 pm](https://cloud.githubusercontent.com/assets/3353209/4082285/1b2b9bbe-2ef0-11e4-99b2-6d90a77cb9ef.png)

But this in html:

![screen shot 2014-08-28 at 4 16 16 pm](https://cloud.githubusercontent.com/assets/3353209/4082290/336557c4-2ef0-11e4-888b-d979d0998f7c.png)

**Comment by kisonecat** [comment]
This is now fixed.
![2018-03-18-235551_1920x1080_scrot](https://user-images.githubusercontent.com/148352/37577332-03c94b7a-2b08-11e8-92a5-e04acb803038.png)
