### ISSUE TITLE
/mooculus/lengthOfCurves/exercises/exerciseList/lengthOfCurves/exercises/calculateArclength5

### ISSUE THREAD

**Issue by stephenkrivenki** [XimeraProject/server#494]
Why are redundant absolute value signs counted as incorrect? Isn't this akin to leaving a polynomial unsimplified (an unevaluated quantity, for example)?

**Comment by kisonecat** [comment]
That is frustrating.  This is a limitation with the [current answer evaluator](https://github.com/Doenet/math-expressions).  Namely, we do not impose an assumption on _r_, so |_r_| and _r_ are different which wouldn't be the case if the backend knew that _r_ > 0.  I hope the new backend will fix this.
