### ISSUE TITLE
Can't add columns

### ISSUE THREAD

**Issue by ssawatzky** [XimeraProject/server#5]
![screen shot 2014-03-20 at 11 05 29 pm](https://f.cloud.github.com/assets/7018702/2480196/0137703c-b0b2-11e3-812f-0cd6ce4c5fd9.png)

Clicking the plus/minus buttons don't do anything for this particular page (in Chrome). However all other plus/minus buttons seem to be working.

**Comment by kisonecat** [comment]
We've eliminated the matrix answer type for the time being...  A complete rewrite is forthcoming.
