### ISSUE TITLE
comment environment

### ISSUE THREAD

**Issue by StevenGubkin** [XimeraProject/server#53]
It would be nice to have a \begin{comment} \end{comment} environment. 

This would be somewhat nicer than using lots of %'s. 

I am thinking that the code in this environment would be parsed but not displayed, so that we could auto-check code which we currently want commented out.  Example usage:

\begin{comment}
%Maybe a problem like this would be nice?

The mightiest god is \answr{Crom}.
\end{comment}

When I push a commit containing this code, the un%'ed part of it would be parsed, and would identify the fact that I misspelled \answer.  If I didn't use the comment environment, and instead just %'ed every line, then this would not be checked, and I would have to use a lot of %'s

**Comment by kisonecat** [comment]
There are environments like this that can be pulled in just via TeX -- see https://tex.stackexchange.com/questions/17816/commenting-out-large-sections
