### ISSUE TITLE
multiple response multiple choice

### ISSUE THREAD

**Issue by StevenGubkin** [XimeraProject/server#54]
We should support something like the following:

\begin{question}
What are valid reasons to use Ximera?
\begin{multiple-choice}
\choice[correct]{ To share your love of mathematics with the world}
\choice[correct]{ To impress your friends and loved ones with your stunningly original content}
\choice{As a vehicle for injecting bitcoin mining malware on your students PC's}
\choice{As a blogging platform about my little pony}
\end{multiple-choice}
\end{question}

The user would then have to select both correct answers to answer the question correctly.  We should probably have some sort of auto-feedback system of the form "X was not right, but the rest of your choices were", or "Everything you selected was correct but there is still one more correct response which you have not selected."

**Comment by kisonecat** [comment]
This is implemented with \begin{selectAll} now.
