### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by crgibbons** [XimeraProject/server#57]
I've got a lovely table in my .tex and .pdf files, but it looks pretty weird on the web:
http://ximera.osu.edu/course/crgibbons/Cryptography/course/activity/NumbersInOtherBases/NumbersInOtherBases/

**Comment by kisonecat** [comment]
I'm in the process of making some significant changes to the TeX-to-HTML
process, which should address this.


~jim

**Comment by crgibbons** [comment]
Awesome! Thanks for the heads up!

**Comment by kisonecat** [comment]
https://github.com/XimeraProject/server/commit/7d1fa4dc152183f81467943899d7b5a9f83a630e fixes tables.
