### ISSUE TITLE
Table answer type

### ISSUE THREAD

**Issue by StevenGubkin** [XimeraProject/server#60]
It would be nice to have a table answer type.  For example,

\begin{tableanswer}
 x & f(x) \ \hline
 1.7 &  \answer{0.7} \
 1.9 &  \answer{0.9} \
 1.99 &  \answer{0.99}\
 1.999 &   \answer{0.999} \
 2 &  \text{undefined}
 2.001&   \answer{1.001}\
 2.01&   \answer{1.01}\
 2.1 &   \answer{1.1} \
 2.3 &   \answer{1.3} \
\end{tableanswer}
]

**Comment by kisonecat** [comment]
Should this work with a regular table or array?

**Comment by bartsnapp** [comment]
This should be covered by  our "multiple" answers in an environment.... right?

**Comment by StevenGubkin** [comment]
Bart proposes that just

\begin{question}
\begin{table}
...
\end{table}
\end{question}

should work where you just include answers wherever you want within the
table.  I agree with this in principle, but not sure how easy it is to
implement.

**Comment by kisonecat** [comment]
This is working now.
