### ISSUE TITLE
Not taking the answer

### ISSUE THREAD

**Issue by pfatheddin** [XimeraProject/server#617]
https://ximera.osu.edu/mooculus/approximatingTheAreaUnderACurve/exercises/exerciseList/approximatingTheAreaUnderACurve/exercises/05_03_ex_25

I keep putting in the answer and it won't say it is right or wrong and won't take it.

**Comment by bartsnapp** [comment]
![image](https://github.com/user-attachments/assets/daf11225-4ed9-4c0c-903d-5f5125902995)

Seems good now

**Comment by pfatheddin** [comment]
Ok. Thank you.
