### ISSUE TITLE
Exploration environment is not styled

### ISSUE THREAD

**Issue by nbloomf** [XimeraProject/server#71]
The exploration environment is not styled (with a box and title, like problems and questions are).

Example here:

http://497a6980.ngrok.com/course/nbloomf/CollegeAlgebra/master/Garden/Garden

(The paragraph starting with "The length of the rectangle below..." and the geogebra embed are in an exploration environment.)

**Comment by kisonecat** [comment]
\begin{exploration} is now styled.
