### ISSUE TITLE
\paragraph tag too subtle

### ISSUE THREAD

**Issue by bartsnapp** [XimeraProject/server#81]
Initially I thought it was being ignored, but now I just think it is subtle.

**Comment by kisonecat** [comment]
Can you link to an activity employing it?

**Comment by bartsnapp** [comment]
Check out 

https://ximera.osu.edu/course/mooculus/mooculus/master/textbook/asymptotesAsLimits/digInSlantAsymptotes

there should be a paragraph that says "Horizontal asymptotes" "Vertical asymptotes" and "Slant asymptotes"

**Comment by kisonecat** [comment]
It's bolded now which I hope is enough.
