### ISSUE TITLE
Tabular in XImera

### ISSUE THREAD

**Issue by bartsnapp** [XimeraProject/server#88]
Tabular renders a table with black vertical rules and light grey horizontal rules. 

See

https://ximera.osu.edu/course/mooculus/mooculus/development/textbook/higherOrderDerivativesAndGraphs/digInConcavity

at some point this should be fixed.

**Comment by kisonecat** [comment]
Tables are now using bootstrap tables in https://github.com/XimeraProject/server/commit/7d1fa4dc152183f81467943899d7b5a9f83a630e
