### ISSUE TITLE
Week 1, Higher Order Functions

### ISSUE THREAD

**Issue by jplolo** [XimeraProject/server#9]
Would like to add an original comment but there is no option.  I try adding to someone else's comment and it says, POST or DELETE, but no text window to write.  Not sure how to ask a question about the content.
![screen shot 2014-03-30 at 11 50 01](https://cloud.githubusercontent.com/assets/7066042/2562597/6a8f0626-b855-11e3-8eaa-1f9b6326f23d.png)

**Comment by kisonecat** [comment]
We've rewritten the forum code (and well, now it is entirely gone) so I'm closing this.
