### ISSUE TITLE
Strange Rendering Error in align*

### ISSUE THREAD

**Issue by bartsnapp** [XimeraProject/server#92]
There is a strange error midway down the page
it displays:

<!−−l.106−−><pclass="noindent">

https://ximera.osu.edu/course/mooculus/mooculus/master/textbook/implicitDifferentiation/digInImplicitDifferentiation

**Comment by kisonecat** [comment]
I have updated xake to version 0.1.20 to remove line numbers from the HTML before xake publish sends the HTML to the server.  This should fix this bug.

(An alternative solution would involve removing the line numbers from tex4ht, but line numbers are emitting in multiple places in tex4ht and I'm worried about messing around too much with the tex4h side of things.)

**Comment by kisonecat** [comment]
I have horrible memories of this bug, but this is fixed now.
