### ISSUE TITLE
\frac{-1}{2} \ne -\frac{1}{2}

### ISSUE THREAD

**Issue by bartsnapp** [XimeraProject/server#93]
It seems that these validate differently

**Comment by StevenGubkin** [comment]
Can you point us to an instance of this failure?

**Comment by bartsnapp** [comment]
Two (or more commits) behind the current master in 

https://ximera.osu.edu/course/mooculus/mooculus/master/textbook/derivativesOfInverseFunctions/digInDerivativesOfInverseTrigonometricFunctions

in the questions involving the range of arcsin and arctan, 

\answer{-\frac{\pi}{2}}  was unanswerable

and 

\answer{\frac{-\pi}{2}} is answerable

**Comment by kisonecat** [comment]
These are both answerable now.
