### ISSUE TITLE
Reveal Hint Button

### ISSUE THREAD

**Issue by bartsnapp** [XimeraProject/server#94]
At some point, we need to have this move from where it is. 

In 

https://ximera.osu.edu/course/mooculus/mooculus/master/textbook/computationsForGraphingFunctions/digInComputationsForGraphingFunctions

the hints are so long that you have to move up and down to find the button.

**Comment by StevenGubkin** [comment]
I went through the exercise and it is a little klunky, but quite bearable
with the ability to minimize hints.  No individual hint was so long that I
had to scroll up to hit the "reveal hint" button.  Maybe this would not be
the case with different display settings (like on an iPhone or something).

**Comment by kisonecat** [comment]
It looks like the hints were removed from that activity entirely.
