### ISSUE TITLE
Weird Validator issue with \frac

### ISSUE THREAD

**Issue by bartsnapp** [XimeraProject/server#98]
In
http://github.com/mooculus/mooculus/edit/master/textbook/substitution/digInIdeaOfSubstitution.tex

with the final "answer" of this example/explanation combo

```
\begin{example}
Compute
\[
\int x^4(x^5+1)^{99} \d x.
\]
\begin{explanation}
Here we set $g(x) =  \answer[given]{x^5+1}$, so $\d g =  \answer[given]{5x^4} \d x$.  Then
\begin{align*}
  \int x^4(x^5+1)^{99} \d x &= \frac{1}{5} \int 5x^4 (x^5+1)^{99} \d x \\
  &= \frac{1}{5} \int g^{99} \d g\\
&= \answer[given]{\frac{g^{100}}{500}}.
\end{align*}
Notice that this example is an indefinite integral and not a definite integral, meaning that there are no endpoints on the integral.  
So we do not need to worry about changing the endpoints of the integral.  
But we do need to back-substitute into our answer, so that our final answer is a function of $x$.  
Recalling that $g(x) =  x^5+1$, we have our final answer
\[
\int x^4(x^5+1)^{99} \d x= \answer[given]{\frac{(x^5+1)^{100}}{500}}+C.
\]
\end{explanation}
\end{example}
```

while (x^5+1)^100/500 is accepted, (1/5)*(x^5+1)^100/100 is not

This is so weird it should tell us something about how this is broken.

**Comment by StevenGubkin** [comment]
This likely has to do with how floating point arithmetic works.  For such
huge numbers (on the order of 10^100 being tested) multiplication will not
be commutative.  This is part of the reason we should be doing syntactic
comparison first, and falling back to numerical when it does not.

**Comment by StevenGubkin** [comment]
(For now, I would suggest avoiding things like x^100, and stick to maybe
x^10?)

**Comment by kisonecat** [comment]
This will be fixed once we include the new version of kisonecat/math-expressions
